### ISSUE TITLE
WinCoot 0.8.9-pre-revision-7109 installer broken

### ISSUE THREAD

**Issue by ProustIdee** [bernhardcl/coot#1]
Gives error message:

```
Error in Installation. Aborting!

Error in installation. Could not initiate installation.
```

WinCoot-0.8.9-pre-revision-6792.exe and WinCoot-0.8.8.exe both work fine. I re-downloaded 3 times to check the file.

**Comment by pemsley** [comment]
From where did you get this exe?

**Comment by bernhardcl** [comment]
Thanks for the report. It is broken indeed. I will remove the installer and try to get a working one up and running soon.

**Comment by ProustIdee** [comment]
WinCoot 0.8.9-pre-revision-7109 installer works great, thanks!
