### ISSUE TITLE
Missing MD5 for 1.0.01

### ISSUE THREAD

**Issue by eusebiu** [bernhardcl/coot#10]
MD5 file is missing for release 1.0.01.

**Comment by bernhardcl** [comment]
Indeed and purposely (sort of). This is not an installer and hence I omitted the md5sum. If necessary I can add it. It will come once we have an installer...

**Comment by eusebiu** [comment]
ok. please attach the file

**Comment by eusebiu** [comment]
Hey @bernhardcl !
Can you help us with a timeline for the installer (with the md5sum)? 
Thanks!
