### ISSUE TITLE
x64 build ?

### ISSUE THREAD

**Issue by inter1965** [bernhardcl/coot#2]
Is there a x64 build based on msys2 (x86_64-w64-mingw32)?

**Comment by bernhardcl** [comment]
Yes (on my computer). Well, it is planned and I can send you the build file (no warranties and little to no support). At the moment I am prioritising getting the ligand enhanced version out (almost there) as the packaging from the msys2 build (unless you use msys2) looks non-trivial (I need to hunt for all sorts of dependencies).
B

**Comment by bernhardcl** [comment]
build-it-win64 does the trick now. And there are some 64bit test releases (all 0.9 are 64 bit).
B
