### ISSUE TITLE
Map not properly displayed.

### ISSUE THREAD

**Issue by inter1965** [bernhardcl/coot#7]
![coot](https://user-images.githubusercontent.com/735802/79203869-4063b500-7e6e-11ea-811a-73863242e203.png)
compared to the last version of wincoot

**Comment by bernhardcl** [comment]
This may be due to a difference in contour level. Please check your contour level.

**Comment by inter1965** [comment]
Actually i checked displayed using different contour levels however without any changes.

**Comment by pemsley** [comment]
Check that the map is OK by looking at the map density histogram. Check that the rotation centre is the same in both cases - you would not expect the map to look the same it was different.
